package adapter

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"sync"
	"text/template"

	"openforge/internal/shared/kernel"
)

// NginxLoadBalancer implements kernel.LoadBalancer using an in-memory pool
// and optional nginx configuration file generation.
type NginxLoadBalancer struct {
	mu          sync.RWMutex
	backends    map[string][]string // name -> list of addresses
	configPath  string              // Path to nginx upstream config file
	enabled     bool
}

// nginxUpstreamTemplate is the template for nginx upstream configuration.
const nginxUpstreamTemplate = `# Auto-generated by OpenForge LoadBalancer
# Do not edit manually - changes will be overwritten
{{range $name, $addrs := .Backends}}
upstream {{$name}} {
{{range $addr := $addrs}}    server {{$addr}};
{{end}}}
{{end}}
`

// NewNginxLoadBalancer creates a new nginx load balancer.
// If configPath is empty, it operates in memory-only mode.
func NewNginxLoadBalancer(configPath string) *NginxLoadBalancer {
	lb := &NginxLoadBalancer{
		backends:   make(map[string][]string),
		configPath: configPath,
		enabled:    true,
	}

	slog.Info("nginx load balancer enabled", "config_path", configPath)
	return lb
}

// AddBackend adds a backend server to the specified pool.
func (n *NginxLoadBalancer) AddBackend(ctx context.Context, name string, addr string) error {
	if !n.enabled {
		return fmt.Errorf("nginx load balancer is disabled")
	}

	n.mu.Lock()
	defer n.mu.Unlock()

	// Check if backend already exists
	for _, existing := range n.backends[name] {
		if existing == addr {
			return nil // Already exists
		}
	}

	// Add to pool
	n.backends[name] = append(n.backends[name], addr)
	slog.Info("added backend", "pool", name, "addr", addr)

	// Update nginx config if path is set
	if n.configPath != "" {
		if err := n.writeConfig(); err != nil {
			slog.Warn("failed to update nginx config", "error", err)
			// Don't return error - in-memory update succeeded
		}
	}

	return nil
}

// RemoveBackend removes a backend server from the specified pool.
func (n *NginxLoadBalancer) RemoveBackend(ctx context.Context, name string, addr string) error {
	if !n.enabled {
		return fmt.Errorf("nginx load balancer is disabled")
	}

	n.mu.Lock()
	defer n.mu.Unlock()

	backends := n.backends[name]
	for i, existing := range backends {
		if existing == addr {
			// Remove from slice
			n.backends[name] = append(backends[:i], backends[i+1:]...)
			slog.Info("removed backend", "pool", name, "addr", addr)

			// Clean up empty pool
			if len(n.backends[name]) == 0 {
				delete(n.backends, name)
			}

			// Update nginx config if path is set
			if n.configPath != "" {
				if err := n.writeConfig(); err != nil {
					slog.Warn("failed to update nginx config", "error", err)
				}
			}

			return nil
		}
	}

	return fmt.Errorf("backend %s not found in pool %s", addr, name)
}

// HealthCheck returns true if the specified pool has at least one backend.
func (n *NginxLoadBalancer) HealthCheck(ctx context.Context, name string) (bool, error) {
	if !n.enabled {
		return false, fmt.Errorf("nginx load balancer is disabled")
	}

	n.mu.RLock()
	defer n.mu.RUnlock()

	backends, exists := n.backends[name]
	if !exists {
		return false, nil
	}

	return len(backends) > 0, nil
}

// writeConfig writes the nginx upstream configuration file.
func (n *NginxLoadBalancer) writeConfig() error {
	tmpl, err := template.New("nginx").Parse(nginxUpstreamTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	// Create temporary file first, then rename for atomic update
	tempPath := n.configPath + ".tmp"
	file, err := os.Create(tempPath)
	if err != nil {
		return fmt.Errorf("failed to create temp file: %w", err)
	}
	defer file.Close()

	data := struct {
		Backends map[string][]string
	}{
		Backends: n.backends,
	}

	if err := tmpl.Execute(file, data); err != nil {
		os.Remove(tempPath)
		return fmt.Errorf("failed to execute template: %w", err)
	}

	file.Close()

	// Atomic rename
	if err := os.Rename(tempPath, n.configPath); err != nil {
		os.Remove(tempPath)
		return fmt.Errorf("failed to rename config file: %w", err)
	}

	slog.Info("updated nginx config", "path", n.configPath, "pools", len(n.backends))
	return nil
}

// GetBackends returns the list of backends for a given pool (for testing).
func (n *NginxLoadBalancer) GetBackends(name string) []string {
	n.mu.RLock()
	defer n.mu.RUnlock()

	backends := make([]string, len(n.backends[name]))
	copy(backends, n.backends[name])
	return backends
}

// ListPools returns all pool names (for testing).
func (n *NginxLoadBalancer) ListPools() []string {
	n.mu.RLock()
	defer n.mu.RUnlock()

	pools := make([]string, 0, len(n.backends))
	for name := range n.backends {
		pools = append(pools, name)
	}
	return pools
}

// Close cleans up resources.
func (n *NginxLoadBalancer) Close() error {
	// Nothing to clean up for in-memory implementation
	return nil
}

// Verify that NginxLoadBalancer implements kernel.LoadBalancer.
var _ kernel.LoadBalancer = (*NginxLoadBalancer)(nil)