-- 001_init.down.sql — DROP ALL Phase 1 tables (dev only)
DROP TABLE IF EXISTS task_queue CASCADE;
DROP TABLE IF EXISTS feature_flag CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS cost_quota CASCADE;
DROP TABLE IF EXISTS token_usage CASCADE;
DROP TABLE IF EXISTS file_lock CASCADE;
DROP TABLE IF EXISTS conversation_branch CASCADE;
DROP TABLE IF EXISTS conversation_message CASCADE;
DROP TABLE IF EXISTS checkpoint CASCADE;
DROP TABLE IF EXISTS gate_event CASCADE;
DROP TABLE IF EXISTS pipeline_stage CASCADE;
DROP TABLE IF EXISTS pipeline CASCADE;
DROP TABLE IF EXISTS module_ownership CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS project CASCADE;
