package compliance

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// ReportType identifies which compliance report to generate.
type ReportType string

const (
	ReportAudit   ReportType = "audit"
	ReportAccess  ReportType = "access"
	ReportData    ReportType = "data"
	ReportLicense ReportType = "license"
)

// AllReportTypes is the ordered list of report types generated by the
// monthly scheduler.
var AllReportTypes = []ReportType{ReportAudit, ReportAccess, ReportData, ReportLicense}

// Report is the top-level compliance report payload.
type Report struct {
	Type     ReportType      `json:"type"`
	Month    string          `json:"month"` // YYYY-MM
	Title    string          `json:"title"`
	Sections []ReportSection `json:"sections"`
	// GeneratedAt is when this report was assembled.
	GeneratedAt time.Time `json:"generated_at"`
}

// ReportSection groups rows under a heading.
type ReportSection struct {
	Title string      `json:"title"`
	Rows  []ReportRow `json:"rows"`
}

// ReportRow is one aggregated fact in a section.
type ReportRow struct {
	Label string `json:"label"`
	Count int64  `json:"count"`
}

// SBOMScanner is the interface used by the license report. The
// concrete implementation lives in sbom_generator.go (SyftSBOMScanner
// backed by the `syft` CLI) but the report generator depends only on
// the interface so tests can substitute a mock. SBOMScanner is
// forward-declared here; the canonical definition is in
// sbom_generator.go.
//
// sbomScanner may be nil on ReportGenerator; the license report
// returns an empty Dependencies section in that case (T8 stub
// behaviour, preserved by T9).
//
// Rows is the abstract row iterator used by the report generator. The
// production wiring wraps *sql.Rows in sqlRowsAdapter; tests plug in
// fakeRows that satisfy the same interface without a real driver.
type Rows interface {
	Next() bool
	Scan(dest ...any) error
	Close() error
	Err() error
}

// rowQuerier abstracts the small slice of *sql.DB used by the report
// generator so tests can plug in an in-memory implementation without
// pulling in a CGO sqlite driver.
type rowQuerier interface {
	QueryContext(ctx context.Context, query string, args ...any) (Rows, error)
	QueryRowContext(ctx context.Context, query string, args ...any) Rows
}

// sqlRowsAdapter wraps *sql.Rows so the production *sql.DB satisfies
// the rowQuerier interface.
type sqlRowsAdapter struct{ inner *sql.Rows }

func (a *sqlRowsAdapter) Next() bool         { return a.inner.Next() }
func (a *sqlRowsAdapter) Scan(d ...any) error { return a.inner.Scan(d...) }
func (a *sqlRowsAdapter) Close() error       { return a.inner.Close() }
func (a *sqlRowsAdapter) Err() error         { return a.inner.Err() }

// sqlDBQuerier wraps a *sql.DB so the production wiring returns the
// abstract Rows type.
type sqlDBQuerier struct{ db *sql.DB }

func (q *sqlDBQuerier) QueryContext(ctx context.Context, query string, args ...any) (Rows, error) {
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	return &sqlRowsAdapter{inner: rows}, nil
}
func (q *sqlDBQuerier) QueryRowContext(ctx context.Context, query string, args ...any) Rows {
	rows, err := q.db.QueryContext(ctx, query, args...)
	if err != nil {
		return &errRows{err: err}
	}
	return &sqlRowsAdapter{inner: rows}
}

// errRows is a Rows that immediately reports an error and is empty.
type errRows struct{ err error }

func (e *errRows) Next() bool         { return false }
func (e *errRows) Scan(_ ...any) error { return e.err }
func (e *errRows) Close() error       { return nil }
func (e *errRows) Err() error         { return e.err }

// ReportGenerator builds monthly compliance reports from the database
// and SBOM scan results.
type ReportGenerator struct {
	db          rowQuerier
	sbomScanner SBOMScanner // may be nil; license report returns empty rows in that case
}

// NewReportGenerator creates a new ReportGenerator.
// sbomScanner may be nil; when nil the license report returns an
// empty Dependencies section (matches T8 stub behaviour).
func NewReportGenerator(db *sql.DB, scanner SBOMScanner) *ReportGenerator {
	return &ReportGenerator{db: &sqlDBQuerier{db: db}, sbomScanner: scanner}
}

// newReportGeneratorWithQuerier is a test seam allowing an in-memory
// rowQuerier to be substituted for *sql.DB. Production code uses
// NewReportGenerator.
func newReportGeneratorWithQuerier(q rowQuerier) *ReportGenerator {
	return &ReportGenerator{db: q}
}

// Generate dispatches to the per-type builder. The license report
// delegates to the wired SBOM scanner; when no scanner is wired it
// returns an empty Dependencies section so the scheduler can iterate
// the full catalog.
func (g *ReportGenerator) Generate(ctx context.Context, t ReportType, month string) (*Report, error) {
	if err := validateMonth(month); err != nil {
		return nil, err
	}
	switch t {
	case ReportAudit:
		return g.auditReport(ctx, month)
	case ReportAccess:
		return g.accessReport(ctx, month)
	case ReportData:
		return g.dataReport(ctx, month)
	case ReportLicense:
		return g.licenseReport(ctx, month)
	default:
		return nil, fmt.Errorf("compliance: unknown report type %q", t)
	}
}

// auditReport aggregates audit_log by action for the given month.
func (g *ReportGenerator) auditReport(ctx context.Context, month string) (*Report, error) {
	r := &Report{
		Type:        ReportAudit,
		Month:       month,
		Title:       "Audit Activity Report",
		GeneratedAt: time.Now().UTC(),
	}
	rows, err := g.db.QueryContext(ctx, auditByActionQuery, month+"-01")
	if err != nil {
		return nil, fmt.Errorf("audit report query: %w", err)
	}
	defer rows.Close()

	section := ReportSection{Title: "Actions"}
	for rows.Next() {
		var row ReportRow
		if err := rows.Scan(&row.Label, &row.Count); err != nil {
			return nil, fmt.Errorf("audit report scan: %w", err)
		}
		section.Rows = append(section.Rows, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	r.Sections = []ReportSection{section}
	return r, nil
}

// accessReport aggregates login events from audit_log by user_id.
func (g *ReportGenerator) accessReport(ctx context.Context, month string) (*Report, error) {
	r := &Report{
		Type:        ReportAccess,
		Month:       month,
		Title:       "User Access Report",
		GeneratedAt: time.Now().UTC(),
	}
	rows, err := g.db.QueryContext(ctx, accessByActorQuery, month+"-01")
	if err != nil {
		return nil, fmt.Errorf("access report query: %w", err)
	}
	defer rows.Close()

	section := ReportSection{Title: "Logins by User"}
	for rows.Next() {
		var row ReportRow
		if err := rows.Scan(&row.Label, &row.Count); err != nil {
			return nil, fmt.Errorf("access report scan: %w", err)
		}
		section.Rows = append(section.Rows, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	r.Sections = []ReportSection{section}
	return r, nil
}

// dataReport summarises soft-deletion activity in the project table.
func (g *ReportGenerator) dataReport(ctx context.Context, month string) (*Report, error) {
	r := &Report{
		Type:        ReportData,
		Month:       month,
		Title:       "Data Lifecycle Report",
		GeneratedAt: time.Now().UTC(),
	}

	monthStart := month + "-01"

	softDeleted, err := scalarCount(ctx, g.db, softDeletedInMonthQuery, monthStart)
	if err != nil {
		return nil, fmt.Errorf("data report (soft-deleted): %w", err)
	}
	activeProjects, err := scalarCount(ctx, g.db, activeProjectsQuery)
	if err != nil {
		return nil, fmt.Errorf("data report (active): %w", err)
	}
	pendingPurge, err := scalarCount(ctx, g.db, pendingPurgeQuery, monthStart)
	if err != nil {
		return nil, fmt.Errorf("data report (pending purge): %w", err)
	}

	r.Sections = []ReportSection{{
		Title: "Projects",
		Rows: []ReportRow{
			{Label: "soft_deleted", Count: softDeleted},
			{Label: "active", Count: activeProjects},
			{Label: "pending_purge", Count: pendingPurge},
		},
	}}
	return r, nil
}

// scalarCount runs a query expected to return a single int64 column
// (e.g. COUNT(*)) and returns the value. Using QueryContext keeps
// the rowQuerier interface minimal and lets tests stand in
// synthetic rows.
func scalarCount(ctx context.Context, q rowQuerier, query string, args ...any) (int64, error) {
	rows, err := q.QueryContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return 0, err
		}
		return 0, sql.ErrNoRows
	}
	var v int64
	if err := rows.Scan(&v); err != nil {
		return 0, err
	}
	return v, nil
}

// licenseReport delegates to the SBOM scanner (if wired) to discover
// GPL/AGPL-licensed dependencies. When the scanner is nil — the
// pre-T9 stub behaviour — it returns an empty Dependencies section so
// the monthly scheduler can iterate the full report catalog without
// special-casing the license report.
//
// Any error from the scanner is propagated to the caller; the
// scheduler may choose to skip the month or to surface the failure in
// its own logging.
func (g *ReportGenerator) licenseReport(ctx context.Context, month string) (*Report, error) {
	rep := &Report{
		Type:        ReportLicense,
		Month:       month,
		Title:       "License Inventory Report",
		GeneratedAt: time.Now().UTC(),
		Sections:    []ReportSection{{Title: "Dependencies"}},
	}
	if g.sbomScanner == nil {
		return rep, nil
	}
	rows, err := g.sbomScanner.ScanForGplAgpl(ctx)
	if err != nil {
		return nil, fmt.Errorf("license report (sbom scan): %w", err)
	}
	rep.Sections[0].Rows = rows
	return rep, nil
}

// validateMonth ensures the month string is YYYY-MM.
func validateMonth(month string) error {
	_, err := time.Parse("2006-01", month)
	if err != nil {
		return fmt.Errorf("compliance: invalid month %q (want YYYY-MM)", month)
	}
	return nil
}

// Production query strings. Kept as package-level consts so the test
// shim can recognise them and return synthetic rows without executing
// real SQL.
const (
	auditByActionQuery = "SELECT action, COUNT(*) FROM audit_log WHERE created_at >= $1::date AND created_at < ($1::date + INTERVAL '1 month') GROUP BY action ORDER BY 2 DESC, 1 ASC"

	accessByActorQuery = "SELECT actor, COUNT(*) FROM audit_log WHERE action = 'login' AND created_at >= $1::date AND created_at < ($1::date + INTERVAL '1 month') GROUP BY actor ORDER BY 2 DESC, 1 ASC"

	softDeletedInMonthQuery = "SELECT COUNT(*) FROM project WHERE deleted_at IS NOT NULL AND deleted_at >= $1::date AND deleted_at < ($1::date + INTERVAL '1 month')"

	activeProjectsQuery = "SELECT COUNT(*) FROM project WHERE deleted_at IS NULL"

	pendingPurgeQuery = "SELECT COUNT(*) FROM project WHERE deleted_at IS NOT NULL AND deleted_at >= $1::date AND deleted_at < ($1::date + INTERVAL '1 month') AND deleted_at > NOW() - INTERVAL '30 days'"
)
